# Generated by Django 2.2.5 on 2019-11-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_product_product_image_product_size_size_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_image',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
