# Generated by Django 2.2.5 on 2019-11-20 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0005_product_image_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_image',
            old_name='title',
            new_name='name',
        ),
    ]
