# Generated by Django 2.2.5 on 2019-11-24 12:49

from django.db import migrations, models
import showcase.models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0008_product_spring'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_image',
            name='image_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product_image',
            name='image',
            field=models.ImageField(upload_to=showcase.models.image_folder),
        ),
    ]
