# Generated by Django 2.2.5 on 2019-11-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0009_auto_20191124_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_image',
            name='main_image',
            field=models.BooleanField(default=False),
        ),
    ]
