# Generated by Django 2.2.5 on 2019-12-05 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0013_auto_20191205_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='full_title',
            new_name='short_title',
        ),
    ]
