# Generated by Django 2.2.5 on 2019-12-13 12:11

from django.db import migrations, models
import showcase.models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0014_auto_20191205_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=showcase.models.image_folder)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
