# Generated by Django 2.2.5 on 2020-01-14 19:33

from django.db import migrations, models
import showcase.models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0017_auto_20200112_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=showcase.models.image_folder)),
            ],
        ),
    ]
