# Generated by Django 2.2.5 on 2020-01-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0018_cataloguefile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cataloguefile',
            options={'verbose_name': 'Каталог', 'verbose_name_plural': 'Кататалог'},
        ),
        migrations.AddField(
            model_name='cataloguefile',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cataloguefile',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
