# Generated by Django 2.2.5 on 2020-05-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0020_auto_20200527_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
