# Generated by Django 2.2.5 on 2020-05-27 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0021_product_short_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='short_title',
        ),
    ]
