# Generated by Django 2.2.5 on 2020-05-28 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0022_remove_product_short_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_image',
            name='image_number',
        ),
    ]
