# Generated by Django 2.2.5 on 2020-06-02 18:11

import ckeditor.fields
from django.db import migrations, models
import showcase.models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0023_remove_product_image_image_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('text', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, upload_to=showcase.models.image_folder)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
            },
        ),
    ]
