# Generated by Django 2.2.5 on 2020-06-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0024_slide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('inn', models.CharField(max_length=10)),
                ('ogrn', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
